name: islamic_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  get_storage: ^2.1.1
  get: 4.6.6
  http: ^1.2.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  external_path: ^1.0.3
  flutter: 
    sdk: flutter
  firebase_analytics: ^11.1.0
  firebase_messaging: ^15.0.2
  sqflite: ^2.3.3+1

assets:
  -assets/
dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true