// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADUjKCDms970pAZweV2eMaletQ_Gsn178',
    appId: '1:458967270495:web:6bd706b156cde1ce1207ea',
    messagingSenderId: '458967270495',
    projectId: 'islamic-app-7044c',
    authDomain: 'islamic-app-7044c.firebaseapp.com',
    storageBucket: 'islamic-app-7044c.appspot.com',
    measurementId: 'G-5TXPHWHDL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeA39IBGUiKAnjcYLLcdPjuj3d1S2bvzo',
    appId: '1:458967270495:android:20b8d45734c1f2a61207ea',
    messagingSenderId: '458967270495',
    projectId: 'islamic-app-7044c',
    storageBucket: 'islamic-app-7044c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRxPs_W7SJYLUoo-rRzo8AL5jhW6vF7ws',
    appId: '1:458967270495:ios:db3d35331ac85bee1207ea',
    messagingSenderId: '458967270495',
    projectId: 'islamic-app-7044c',
    storageBucket: 'islamic-app-7044c.appspot.com',
    iosBundleId: 'islamic.com.islamicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRxPs_W7SJYLUoo-rRzo8AL5jhW6vF7ws',
    appId: '1:458967270495:ios:db3d35331ac85bee1207ea',
    messagingSenderId: '458967270495',
    projectId: 'islamic-app-7044c',
    storageBucket: 'islamic-app-7044c.appspot.com',
    iosBundleId: 'islamic.com.islamicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADUjKCDms970pAZweV2eMaletQ_Gsn178',
    appId: '1:458967270495:web:4498b297f064a86d1207ea',
    messagingSenderId: '458967270495',
    projectId: 'islamic-app-7044c',
    authDomain: 'islamic-app-7044c.firebaseapp.com',
    storageBucket: 'islamic-app-7044c.appspot.com',
    measurementId: 'G-MVN7Y4HLYD',
  );
}
